### ISSUE TITLE
'Usage' documentation?

### ISSUE THREAD

**Issue by jdar** [SSKGo/perfcurve-panel#16]
Hello! Thank you for the useful plugin.

Please see the attached screenshot. I cannot show points on the graph?

I see your example, but it is a picture, rather than text. This makes it hard to copy-paste. Also, it is not clear what SQL flavor is being used? https://github.com/SSKGo/perfcurve-panel/blob/master/docs/img/query_example.png

<img width="1121" alt="Screen Shot 2021-05-16 at 10 04 25 PM" src="https://user-images.githubusercontent.com/37452/118435352-ae8f3280-b693-11eb-952c-5483e6918e45.png">

```SQL
SELECT 30 AS avg_va, 5 AS avg_vb, 50 AS avg_amp
FROM $__database.$__table
```

**Comment by SSKGo** [comment]
@jdar 

Thank you for giving a feedback.

I guess the dataframe structure you used is not time series. The purpose of this panel is pump and compressor operation monitoring on performance curves so data should be time series.

I attached snapshot of the example with TestData DB data source, which anyone can use as default. Could you try this example? I hope you can get the dataframe structure idea through this example.

As per your request, I also attached panel JSON, too. You can regenerate the example by copy & paste.  (Don't forget to register TestData DB at Data Sources setting.)

I will add this example in README in future.

![104079110-bf064b00-5264-11eb-969f-59a0ec7535bf](https://user-images.githubusercontent.com/54466390/118779752-568c4200-b8c6-11eb-817f-344af0662a57.png)

![104079361-e873a680-5265-11eb-822d-0170ec5e6d07](https://user-images.githubusercontent.com/54466390/118779777-5a1fc900-b8c6-11eb-99b2-393c38ba606e.png)

`
{
  "fieldConfig": {
    "defaults": {},
    "overrides": []
  },
  "gridPos": {
    "h": 9,
    "w": 12,
    "x": 0,
    "y": 0
  },
  "id": 23763571993,
  "options": {
    "xAxis": {
      "minValue": 0,
      "maxValue": 60,
      "label": "Flowrate"
    },
    "yAxis": {
      "minValue": 0,
      "maxValue": 100,
      "label": "Pressure"
    },
    "performanceCurveData": [
      {
        "color": "rgba(136, 136, 136, 0.6)",
        "performCurveX": "10,20,30,40,50",
        "performCurveY": "80,78,72,62,48"
      }
    ],
    "dynamicPerfCurve": [],
    "plotSetting": [
      {
        "color": "#F2495C",
        "label": "Label Name",
        "xField": "Field X",
        "yField": "Field Y"
      }
    ],
    "pointRadius": 2
  },
  "pluginVersion": "7.5.6",
  "targets": [
    {
      "alias": "Field X",
      "csvWave": {
        "timeStep": 60,
        "valuesCSV": "0,0,2,2,1,1"
      },
      "lines": 10,
      "points": [],
      "pulseWave": {
        "offCount": 3,
        "offValue": 1,
        "onCount": 3,
        "onValue": 2,
        "timeStep": 60
      },
      "refId": "A",
      "scenarioId": "csv_metric_values",
      "stream": {
        "bands": 1,
        "noise": 2.2,
        "speed": 250,
        "spread": 3.5,
        "type": "signal"
      },
      "stringInput": "30"
    },
    {
      "alias": "Field Y",
      "csvWave": {
        "timeStep": 60,
        "valuesCSV": "0,0,2,2,1,1"
      },
      "hide": false,
      "lines": 10,
      "points": [],
      "pulseWave": {
        "offCount": 3,
        "offValue": 1,
        "onCount": 3,
        "onValue": 2,
        "timeStep": 60
      },
      "refId": "B",
      "scenarioId": "csv_metric_values",
      "stream": {
        "bands": 1,
        "noise": 2.2,
        "speed": 250,
        "spread": 3.5,
        "type": "signal"
      },
      "stringInput": "50"
    },
    {
      "alias": "Field X1",
      "csvWave": {
        "timeStep": 60,
        "valuesCSV": "0,0,2,2,1,1"
      },
      "hide": false,
      "lines": 10,
      "points": [],
      "pulseWave": {
        "offCount": 3,
        "offValue": 1,
        "onCount": 3,
        "onValue": 2,
        "timeStep": 60
      },
      "refId": "C",
      "scenarioId": "csv_metric_values",
      "stream": {
        "bands": 1,
        "noise": 2.2,
        "speed": 250,
        "spread": 3.5,
        "type": "signal"
      },
      "stringInput": "10, 10"
    },
    {
      "alias": "Field Y1",
      "csvWave": {
        "timeStep": 60,
        "valuesCSV": "0,0,2,2,1,1"
      },
      "hide": false,
      "lines": 10,
      "points": [],
      "pulseWave": {
        "offCount": 3,
        "offValue": 1,
        "onCount": 3,
        "onValue": 2,
        "timeStep": 60
      },
      "refId": "D",
      "scenarioId": "csv_metric_values",
      "stream": {
        "bands": 1,
        "noise": 2.2,
        "speed": 250,
        "spread": 3.5,
        "type": "signal"
      },
      "stringInput": "70, 65"
    },
    {
      "alias": "Field X2",
      "csvWave": {
        "timeStep": 60,
        "valuesCSV": "0,0,2,2,1,1"
      },
      "hide": false,
      "lines": 10,
      "points": [],
      "pulseWave": {
        "offCount": 3,
        "offValue": 1,
        "onCount": 3,
        "onValue": 2,
        "timeStep": 60
      },
      "refId": "E",
      "scenarioId": "csv_metric_values",
      "stream": {
        "bands": 1,
        "noise": 2.2,
        "speed": 250,
        "spread": 3.5,
        "type": "signal"
      },
      "stringInput": "20, 20"
    },
    {
      "alias": "Field Y2",
      "csvWave": {
        "timeStep": 60,
        "valuesCSV": "0,0,2,2,1,1"
      },
      "hide": false,
      "lines": 10,
      "points": [],
      "pulseWave": {
        "offCount": 3,
        "offValue": 1,
        "onCount": 3,
        "onValue": 2,
        "timeStep": 60
      },
      "refId": "F",
      "scenarioId": "csv_metric_values",
      "stream": {
        "bands": 1,
        "noise": 2.2,
        "speed": 250,
        "spread": 3.5,
        "type": "signal"
      },
      "stringInput": "68,63"
    }
  ],
  "timeFrom": null,
  "timeShift": null,
  "title": "Panel Title",
  "type": "sskgo-perfcurve-panel",
  "datasource": null
}
`

**Comment by SSKGo** [comment]
Since v1.5.0, the sample setting has been added.
This issue is to be closed.

https://github.com/SSKGo/perfcurve-panel/releases/tag/v1.5.0
