### ISSUE TITLE
New version 1.5.0 not visible in grafana labs

### ISSUE THREAD

**Issue by hellow554** [SSKGo/perfcurve-panel#19]
I can see version 1.4.0 and 1.3.1, I would have to install the new version manually

**Comment by SSKGo** [comment]
Thank you for the comment.
Because of a new Grafana plugin submission procedure, my request to update perfcurve-panel to ver. 1.5.0 was cancelled.
I recreated the request in the new procedure. Now it is under review of Grafana Labs.

**Comment by SSKGo** [comment]
@hellow554 
Version 1.5.0 has been registered.
https://grafana.com/grafana/plugins/sskgo-perfcurve-panel/
