### ISSUE TITLE
Dynamic Curves with influx v2

### ISSUE THREAD

**Issue by Mossi92** [SSKGo/perfcurve-panel#20]
Hi, I cant get the Dynamic performance curve to work with influxdb v2. is there an issue with the dynamic curves or do i need to enter the x and y fields in a different way then described in the readMe file?

**Comment by SSKGo** [comment]
I haven't checked the plugin with influxDB v2. I have checked it only with influxDB v1. If the data frame structure changed at the version up, we need to change something. (Data frame structure totally depends on influxDB datasource plugin.) 
If you don't mind, please share screenshots of the query part and the plugin part.

**Comment by Mossi92** [comment]
![image](https://user-images.githubusercontent.com/71876308/224647720-dbedbfe4-8e01-455f-a51e-5acdfb002d10.png)

I got it working now for some reason.. for influx v2 you need _field and "tag" to get the data.

Thank you anyways.
